// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed-galaxies.ts",
  },
  datasource: {
    // Prisma CLI 전용: DIRECT_URL이 있으면 PgBouncer를 우회하고, 없으면 DATABASE_URL을 사용합니다.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
